### Dictionary Items in Python
Curly braces can define Dictionary items. Or you create a variable of type dict()

In [1]:
E= dict()
E['name']='Sarah'
E['age']=44
E['sex']='Female'

D = {
    'name':'Kailash',
    'age': 47,
    'sex':'Male'
}

print(E.keys())
print(E.values())
print(E.items())

help(sum)

dict_keys(['name', 'age', 'sex'])
dict_values(['Sarah', 44, 'Female'])
dict_items([('name', 'Sarah'), ('age', 44), ('sex', 'Female')])
Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers

    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



In [1]:
sum??

Signature: sum(iterable, /, start=0)
Docstring:
Return the sum of a 'start' value (default: 0) plus an iterable of numbers

When the iterable is empty, return the start value.
This function is intended specifically for use with numeric values and may
reject non-numeric types.
Type:      builtin_function_or_method

In [ ]:

a=[2,3]
b=a
b[1]=5

if(a[1]==b[1]):
	print ('b is a pointer to a')
else: 
	print ('b is a copy of a')
	
id??


### creating a fibonacci sequence using python

In [11]:
fibonacci =[]
a,b=0,1
items = 5
for i in range(items):
    fibonacci.append(a)
    a,b=b,a+b

fibonacci

[0, 1, 1, 2, 3]

In [15]:
[i**(1/2) for i in range (10) if i>5]


[2.449489742783178, 2.6457513110645907, 2.8284271247461903, 3.0]

In [43]:
import numpy as np
arr1 = np.zeros(0,dtype=float)
arr1 = np.append(arr1,3)
arr1

array3 = np.full((12,12), 2)
array3

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

In [32]:
text = 'Hello world! THIS is the DAY!'
vowels = np.zeros(len(text))
for i,t in enumerate(text):
    if t.lower() in 'aeiou':
        vowels[i]=1
vowels

array([0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0.])

In [40]:
numberslist = [i for i in range(5)]
letterslist = ['a','b','c','d','e']

for num,let in zip(numberslist,letterslist):
    print(num**2,let)

for idx,(num,let) in enumerate(zip(numberslist, letterslist)):
    print (idx, num**2, let)

0 a
1 b
4 c
9 d
16 e
0 0 a
1 1 b
2 4 c
3 9 d
4 16 e


In [41]:
waves = ['alpha', 'beta', 'gamma']
freq = [10,20,40]

wavefreq = dict(zip(waves,freq))
wavefreq

{'alpha': 10, 'beta': 20, 'gamma': 40}

In [ ]:
#string stuff
print("hello world %g %s" %(20.5, "Hello")) # order of appearance is important - what are the other print interpolation options?

print("here is the same number in %#x hex and %#o octal and %d decimal" %(100,100,100))

hello world 20.5 Hello
here is the same number in 0x64 hex and 0o144 octal and 100 decimal


In [5]:
import numpy as np
np.random.random_integers(0,50,size=50)


/tmp/ipykernel_55161/3997565317.py:2: DeprecationWarning: This function is deprecated. Please call randint(0, 50 + 1) instead
  np.random.random_integers(0,50,size=50)


array([24,  8, 33, 25, 45,  0, 20, 42, 31,  0, 48, 25, 29, 44, 20, 50, 18,
       48, 18, 34, 14,  4, 36, 45, 19, 43, 32, 45, 44, 36, 30, 14, 28, 26,
       21,  4, 44, 10, 28, 43, 21,  6, 10, 39, 31, 24,  8, 48, 18, 24])