### Definitions
*scalar*: a single number. e.g. 2
*vector*: single dimensional matrix. e.g. [2,3,2]
*matrix*: 2 dimensions or more [[2,2,3],[2,1,0]]


In [108]:
import torch
#v=torch.tensor(1)
v=torch.tensor([[1],[2]])
v, v.shape


(tensor([[1],
         [2]]),
 torch.Size([2, 1]))

In [109]:
#reshape a tensor
w1= torch.tensor([[9,2,3],[4,5,6]])
w2= torch.tensor([[[10,12,-3],[4,5,6]],[[8,10,-1],[2,0,3]]])
print( f'w1>{w1}.\r\n'\
        f' w1.T = {w1.t()}\r\n'\
        f'w2[0]={w2[0]}\r\n'\
        f'flat w1 = {w1.flatten()}'
        )

w1>tensor([[9, 2, 3],
        [4, 5, 6]]).
 w1.T = tensor([[9, 4],
        [2, 5],
        [3, 6]])
w2[0]=tensor([[10, 12, -3],
        [ 4,  5,  6]])
flat w1 = tensor([9, 2, 3, 4, 5, 6])


In [110]:
import numpy
print(w1.view(3,-1))

v2=torch.arange(18).reshape(2,3,-1)
print(v2)

torch.transpose(v2,0,2)

tensor([[9, 2],
        [3, 4],
        [5, 6]])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])


tensor([[[ 0,  9],
         [ 3, 12],
         [ 6, 15]],

        [[ 1, 10],
         [ 4, 13],
         [ 7, 16]],

        [[ 2, 11],
         [ 5, 14],
         [ 8, 17]]])

In [111]:
#Random numbers and permutations
#gaussian distribution

rmat = torch.randn(4,8) # generates a matrix tensor 4x 8 with numbers betwen -1 and 1 with a theoretical mean of 0 and std. distribution of 1
rmat.mean(), rmat.std() # check mean and standard deviation

(tensor(-0.0725), tensor(0.7835))

In [112]:
torch.randint(low=0, high=20, size=(3,2))

tensor([[ 6, 14],
        [ 2, 12],
        [17, 17]])

In [116]:
myspace = torch.linspace(0,30,30,dtype=int)
randperm = torch.randperm(len(myspace))
myspace[randperm] #randomly resort an array

tensor([ 1,  3, 28,  4, 30, 24, 26,  7, 16, 10, 13, 20,  2, 22, 17,  5, 14,  0,
         8,  9, 27, 23, 25, 19, 18,  6, 11, 12, 21, 15])

In [ ]:
name   = 'Alice'
age    = 30
height = 1.73
score  = 95.6789

print(f'Name: {name:10} | Age: {age:5} | Height: {height:4} | Score: {score:}' )

Name: Alice      | Age:    30 | Height: 1.73 | Score: 95.68
